### ISSUE TITLE
Crashing because of forced unwrap of nil value

### ISSUE THREAD

**Issue by nawar** [microsoftgraph/ios-swift-connect-sample#8]
Hi, I'm having issues with your sample, as it crashes every time I'm running it at this line.

https://github.com/microsoftgraph/ios-swift-connect-sample/blob/master/Graph-iOS-Swift-Connect/SendViewController.swift#L118

Probably, you are not counting for the nill values returned from the JSON and force unwrapping them. Any attempt to try to use `guard` or `if let` is futile.

Here's a sample of the data I received. This is the `userInfo` object. 

```Objective-C
{
    "@odata.context" = "https://graph.microsoft.com/v1.0/$metadata#users/$entity";
    businessPhones =     (
    );
    displayName = "<null>";
    givenName = "";
    id = 19c13xxxxxbf7;
    jobTitle = "<null>";
    mail = "<null>";
    mobilePhone = "<null>";
    officeLocation = "<null>";
    preferredLanguage = "<null>";
    surname = "";
    userPrincipalName = "nawar.a.nouri_gmail.com";
}
```

**Comment by jamescro** [comment]
Thanks for drawing this to our attention. We'll see if we can reproduce and report back.

**Comment by jamescro** [comment]
I haven't been able to reproduce this. Given your description of the problem, it looks like part of the problem is that the sample code isn't prepared to use information from the account type that you're using. Are you signing in with an MSA (live.com or outlook.com) or from a school or work account?

**Comment by jamescro** [comment]
It also looks like you could resolve this issue in the short term by changing the line in your link to use the "userPrincipalName" property, which is not null. Could you try that and let me know if it resolves your issue? It looks like the value for "userPrincipalName" in your account won't work as an email address (because of the underscore instead of the ampersand), but the sample wouldn't crash, and you'd be able to hand-edit the address in the text box.

In the long term we'll need to update the sample so that it checks for a non-null "mail" property first and then uses the "userPrincipalName" property if "mail" is null.

**Comment by nawar** [comment]
@jamescro yes, that what I ended up doing, I just wanted to give you guys a heads up to this possible scenario. 

I don't have an outlook/live.com email account, I just created a new [Microsoft account](https://account.microsoft.com) with my gmail email, hence the other null/empty fields. 

And for my email in the response, I changed that myself to avoid getting spammed.

**Comment by jamescro** [comment]
Thanks very much. I'll file a work item for the long term fix. Please reopen or file another issue if you run into other problems.
